### ISSUE TITLE
tone down camera_calibration_parsers error logging

### ISSUE THREAD

**Issue by jack-oquin** [ros-perception/image_common#12]
It would help for camera_calibration_parsers not to complain so loudly when the calibration file being read does not exist:

```
Unable to open camera calibration file
```

This happens normally with camera_info_manager before a camera has been calibrated, and logging it as an error confuses users by making it look like a serious problem. 

I don't want to eliminate error logging completely, because the API only returns true or false, so log messages are needed to determine what went wrong.

But, at least the open error should be dialed back to a warning or even an info message, because it is usually not a problem.

Parse errors and write errors should still be treated seriously.

**Comment by vrabaud** [comment]
ok, added you as member/assignee

**Comment by jack-oquin** [comment]
Working now. Thanks, Vincent.

**Comment by jack-oquin** [comment]
In my judgement, this is not urgent enough to justify fixing in Groovy, post-release.

I'll make the changes when we are ready for Hydro-only updates.

**Comment by vrabaud** [comment]
just start your own branch with it and will merge it if it's not changing behavior too much, and it will be easy to merge for later on for hydro.

**Comment by jack-oquin** [comment]
@vrabaud:

Should I create a change log entry for this? 

How do you feel about maintaining one change log for the entire image_common repo in the metapackae?

**Comment by vrabaud** [comment]
That's with respect to the new REP ? sure, let's do it. The changelog was on the wiki so far.

**Comment by jack-oquin** [comment]
As an experiment, I ran the script @dirk-thomas wrote on this repository. Changes to these packages are uncorrelated, so most of the release entries are blank for most of the packages. 

There are advantages and disadvantages to _per-package_ and _per-repository_ change logs. I wonder if you prefer one or the other. 

Collecting everything into the one _per-repository_ change log in the metapackage will be easier to read. It corresponds to the stack change history on the wiki. But, each entry will need to name the package it describes.

**Comment by vrabaud** [comment]
The per package is actually nicer: easier to clean when you kill/move a package and cleaner when you create a debian package. You're right. I agree with the fact that it's easier to read for a stack though, but image_common has fairly different packages so it is not as useful there I'd say. What's your take ?

**Comment by jack-oquin** [comment]
For this repository, I could go either way. Your point about moving packages is a good one.

You are the maintainer, I am happy to leave it up to you.

**Comment by vrabaud** [comment]
Dude, you're as much of a maintainer as me (if you want to of course :) ). Just make a pull request to officialize it.
Otherwise, Changelog per package it is then/ I also know that at some point, we might have different versions between packages (which makes sense if some don't change), so the changelog should be ready for that. Maybe I should restart that topic on the SIG.

**Comment by jack-oquin** [comment]
Per-package it is. I am convinced by the notion that these packages are not tightly-coupled.

I am willing to help do maintenance. I feel responsible for camera_info_manager, at least. And, it's always nice to have at least two active maintainers.

We already had several discussions about version numbers with @dirk-thomas and @wjwwood. They want every package in a repository to share a common version number. They say that repositories like image_common should be broken up into unary package repositories, if the releases are truly independent. 

That does make sense, but breaking up image_common would mostly create extra maintenance effort without much tangible benefit. So, I suggest that we stick with what we have.

**Comment by jack-oquin** [comment]
@vrabaud: 

Somehow I forgot all about this fix, which still needs to be released to Hydro. I'll make a 1.10.4 release from the hydro-devel branch to Hydro (only), if you agree. To do that, I'll probably need push access to the **ros-gbp/image_common-release** repository, or wherever our bloom stuff goes.

I didn't make any CHANGELOG files yet. I suppose they can wait.

Are there other fixes we should release with this one?

**Comment by jack-oquin** [comment]
Looks like the REP-0127 update, b62aae03bd874a0abc26066e05c27dd7eda9acf8, has not been released, either. 

That should probably go in both Groovy and Hydro. 

If so, maybe we should release 1.10.4 to Groovy and 1.11.0 (with this fix) to Hydro.

**Comment by vrabaud** [comment]
nope, looks good, please release with the changelog and REP 127. Giving you access right now. Thx

**Comment by jack-oquin** [comment]
Do you want me to also release the REP-0127 change to Groovy?

**Comment by vrabaud** [comment]
sure, that will make things cleaner and I think it displays a warning right now. Thank you.

**Comment by jack-oquin** [comment]
Fix released to Hydro: image_common-1.11.0-0, ros/rosdistro#1489.
