### ISSUE TITLE
simple advertise throws illegal instruction on i586

### ISSUE THREAD

**Issue by sdeaderick** [ros-perception/image_common#13]
I am running ros fuerte on roboard-100 with linux ubuntu-10.04 LTS. The roboard is a i596 processor.When I call pub = it.advertise("image_raw", 1); from camera_umd stack this calls throws an illegal instruction. Works fine from i686 computer.

**Comment by jack-oquin** [comment]
It will almost certainly help if you append a gdb stack backtrace for this exception.

**Comment by vrabaud** [comment]
can you please send a piece of code replicating it ? Thx

**Comment by sdeaderick** [comment]
Hi Vincent,

I am running the camera_node from the camera_umd stack. The code that calls
this is in the camera.cpp source from the uvc_camera package.

Scott

**Comment by sdeaderick** [comment]
I will try to get this to you tomorrow.

Scott

**Comment by vrabaud** [comment]
Fuerte is not supported anymore, please re-open if you get it under Hydro or above.
