### ISSUE TITLE
Release image_common to ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/image_common#154]
@vrabaud @jack-oquin would you mind releasing `image_common` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 168 repos need it.

I'm not sure how much work it will need. At a minimum it needs #153. There also seem to be a few PRs with Python 3 fixes; which will be required. This wiki page has some useful info for transitioning a package to Python 3: http://wiki.ros.org/UsingPython3/

**Comment by seanyen** [comment]
This pull request #155 is also helpful for Python3 support. As @sloretz mentioned, this is a package on the critical path of the ROS dependency graph and hope we can move forward and unblock them.

**Comment by sloretz** [comment]
Released in https://github.com/ros/rosdistro/pull/24343 , Thanks @mjcarroll !
