### ISSUE TITLE
camera_info_manager: Initializing from a CameraInfo message instead of a file.

### ISSUE THREAD

**Issue by jbohren** [ros-perception/image_common#19]
Is there a reason why you shouldn't be able to initialize a CameraInfoManager with a CameraInfo message via the c++ API, instead of necessitating a calibration file uri?

**Comment by jack-oquin** [comment]
It is easy to provide a method that sets the current CameraInfo.

The most natural extension to the current API would essentially be a local method that works [almost like the SetCameraInfo service call](http://docs.ros.org/hydro/api/camera_info_manager/html/classcamera__info__manager_1_1CameraInfoManager.html#aae0d9bb3b77bb7e5815debc0a8d3c9e0). That would involve saving the supplied CameraInfo to whatever file the URL selects. 

Is it important not to write that file? Writing the default URL is mostly harmless, and the file need not previously exist.

**Comment by jbohren** [comment]
> Is it important not to write that file? Writing the default URL is mostly harmless, and the file need not previously exist.

This is to make the gazebo ROS camera plugin satisfy the full ROS camera API. In that case, the camera parameters could come from a calibration file, but the current interface pulls them from the URDF/SDF parameters.

**Comment by jack-oquin** [comment]
I think we can do it either way, with or without saving to the file.

I should think about whether setting it without writing the file violates some subtle invariant. Probably not. It's already possible to receive SetCameraInfo but fail to write the file due to something like permission problems.

I don't see any problem with adding a new method for gazebo to use. We can work out the API details fairly easily.

**Comment by jbohren** [comment]
> I don't see any problem with adding a new method for gazebo to use. We can work out the API details fairly easily.

Cool. I just wrote a function to do it. I'm trying it out now, and then I'll send a PR.

As an aside, this is so I can test out a camera calibration pipeline in simulation.

**Comment by jack-oquin** [comment]
We need unit tests for the new interface. That should be straightforward, they will be similar to the [existing service call tests](https://github.com/jhu-lcsr-forks/image_common/blob/1cb8e63dfe98f8eb2e97426bbb782e52e59853ee/camera_info_manager/tests/unit_test.cpp#L404).

**Comment by jbohren** [comment]
Alright, I'll add those before #20 should be merged.

**Comment by jack-oquin** [comment]
I don't mind doing it if you don't have time, but I probably won't get to it any time soon.

**Comment by jbohren** [comment]
> I don't mind doing it if you don't have time, but I probably won't get to it any time soon.

Same here. If I get to it before you do, I'll post here that I'm starting on it.

**Comment by jack-oquin** [comment]
Jon: Your pull request has been moved to hydro-devel by 1bac114804e40c415885ef397c13b860ac137666. 

I still need to write some test cases for it.

**Comment by jack-oquin** [comment]
Version 1.11.3 released to Hydro and Indigo.

Code depending on this enhancement should specify the `version_gte="1.11.3"` attribute.
