### ISSUE TITLE
🏗️👨‍🌾 New warning compiling simple_subscriber_plugin on OS X

### ISSUE THREAD

**Issue by caguero** [ros-perception/image_common#191]
Here's the build job: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/2029/clang/new/

And here's the detailed warning message: https://ci.ros2.org/view/nightly/job/nightly_osx_debug/2029/clang/new/source.6279c041-06c9-44bf-817f-f71c3f2f0ce9/#73

**Comment by clalancette** [comment]
Likely a side-effect of https://github.com/ros-perception/image_common/pull/186, though I don't know why it didn't show up in CI.

**Comment by jacobperron** [comment]
This was fixed in #192
