### ISSUE TITLE
Question about when image transport publishes image messages

### ISSUE THREAD

**Issue by swiz23** [ros-perception/image_common#209]
Is the the image transport library smart enough to only publish images from a node if there's at least one subscrib r? or does it publish images even if there are no subscribers?

Does the same answer hold true for ros1 and ros2?

Thanks

**Comment by eeberhard** [comment]
The publisher checks that the number of subscribers is non-zero before actually publishing the image message when you call the publish method.
```c++
image_transport::Publisher pub = ...;
pub.publish(msg)
```
From my understanding, this is true on the ROS1 (noetic-devel) and ROS2 branches. You can see the implementation in this line:
https://github.com/ros-perception/image_common/blob/cd57529952b65d5180ff27780a0370ab7504e64d/image_transport/src/publisher.cpp#L164

**Comment by swiz23** [comment]
Thanks!
