### ISSUE TITLE
yaml-cpp includes / libraries 

### ISSUE THREAD

**Issue by peter-lehner** [ros-perception/image_common#24]
I would like to know how cmake is expected to find the yaml-cpp headers and library for the camera_calibration_parsers package. On my system the compilation of the camera_calibration_parsers package fails due to missing yaml-cpp include files. 
In https://github.com/ros-perception/image_common/blob/hydro-devel/camera_calibration_parsers/CMakeLists.txt#L14-L18 the cmake script is querying for the yaml-cpp library but only to receive version information. Usually I would expect for an CMake script to use the following statements after finding a requested package with pkgconfig:
include_directories(${YAML_CPP_INCLUDE_DIRS})
link_directories(${YAML_CPP_LIBRARY_DIRS})
target_link_libraries(... ${YAML_CPP_LIBRARIES})
Additionally does any of the information need to be passed to the CATKIN_PKG macro?

**Comment by vrabaud** [comment]
you're right.
In the condition block you mention, can you please try:

```
include_directories(${NEW_YAMLCPP_INCLUDE_DIRS})
```

Does that fix it for you ?

**Comment by peter-lehner** [comment]
This resolves the include issue, nevertheless then its missing the library during linking. I got it to work by changing the code to:

``` cmake
find_package(PkgConfig)
pkg_check_modules(YAML_CPP yaml-cpp)
if(${YAML_CPP_VERSION} VERSION_GREATER 0.5)
  add_definitions(-DHAVE_NEW_YAMLCPP)
endif()
include_directories(${YAML_CPP_INCLUDE_DIRS})
link_directories(${YAML_CPP_LIBRARY_DIRS})

# define the library
add_library(${PROJECT_NAME}
  src/parse.cpp
  src/parse_ini.cpp
  src/parse_yml.cpp
)
target_link_libraries(${PROJECT_NAME} ${YAML_CPP_LIBRARIES} ${catkin_LIBRARIES})
```
