### ISSUE TITLE
camera_calibration_parsers failing on opencv (2.4.9) yml cal file

### ISSUE THREAD

**Issue by ryan0270** [ros-perception/image_common#27]
Using calibration.cpp from the opencv 2.4.9 samples I get the below cal file. camera_calibration_parsers fails when reading this (I believe because all the expected fields aren't there).

-- error message
$ rosrun camera_calibration_parsers convert opencv_cal.yml cal.ini
[ERROR] [1414461553.365594472]: Exception parsing YAML camera calibration:
yaml-cpp: error at line 0, column 0: bad conversion
[ERROR] [1414461553.365688821]: Failed to parse camera calibration from file [opencv_cal.yml]
[ERROR] [1414461553.365757488]: Failed to load camera model from file opencv_cal.yml

-- cal file
%YAML:1.0
calibration_time: "Mon Oct 27 20:27:45 2014"
image_width: 640
image_height: 360
board_width: 4
board_height: 11
square_size: 1.
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 5.4518782107760103e+02, 0., 3.3949807779434110e+02, 0.,
       5.4093187118613309e+02, 1.8137910120437101e+02, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -5.3510759228546356e-01, 3.6901610613018992e-01,
       1.4705016748743088e-02, -3.3927528664456272e-03,
       -1.2799060009168317e-01 ]
avg_reprojection_error: 4.4247810453160386e-01

**Comment by vrabaud** [comment]
Hi, this sample is not even official OpenCV code so we don't support it. You need to write a converter to the format detailed at: http://wiki.ros.org/camera_calibration_parsers#YAML

**Comment by BigeYoung** [comment]
this sample is used everywhere in OpenCV after 3.0 ... Could you please update it and support the newest type, thank you very much!
