### ISSUE TITLE
Merge #276 broke downstream packages

### ISSUE THREAD

**Issue by jmachowinski** [ros-perception/image_common#279]
Hi, 
the recent merge of 'Expose callback groups - backport to iron' (https://github.com/ros-perception/image_common/pull/276)
just broke donwstream packages (e.g. https://github.com/RobotWebTools/web_video_server) , as 
```c++
  Subscriber subscribe(
    const std::string & base_topic, uint32_t queue_size,
    void (* fp)(const ImageConstPtr &),
    const TransportHints * transport_hints = nullptr)
``` 
and 
```c++
  Subscriber subscribe(
    const std::string & base_topic, uint32_t queue_size,
    void (* fp)(const ImageConstPtr &),
    const TransportHints * transport_hints = nullptr,
    const rclcpp::SubscriptionOptions options = rclcpp::SubscriptionOptions())
``` 
are ambiguous.

**Comment by adityapande-1995** [comment]
Opened a PR to revert the change here : https://github.com/ros-perception/image_common/pull/281 until I fix the issue.

**Comment by jmachowinski** [comment]
Recent merges fixed the issue
