### ISSUE TITLE
Add `camera_info_manager_py` to this repo?

### ISSUE THREAD

**Issue by civerachb-cpr** [ros-perception/image_common#331]
Back in the distant past there was a `camera_info_manager_py` package: https://github.com/ros-perception/camera_info_manager_py. It seems this repo has been effectively abandoned, with the last commits being about 8 years ago.

We've [forked that repo](https://github.com/clearpathrobotics/camera_info_manager_py) and are trying to get it re-released for Humble and Jazzy, since it's a dependency of the `axis_camera` driver, which we'd also like to get released. However, we're getting some pushback from OSRF about releasing a fork of the original package.  They've proposed that rather than releasing our fork, that they'd like to see `camera_info_manager_py` merged here and released by your team.  See: https://github.com/ros/rosdistro/pull/43325#issuecomment-2486164358

Are you open to this? If so, I can open merge requests against your Jazzy and Humble branches to add the new package, and then hopefully you can bloom the repo to get it released officially through OSRF's buildfarm.

Conversely, if you don't want to take ownership of `camera_info_manager_py`, or have some alternative proposal to get it released, could you please leave a comment on https://github.com/ros/rosdistro/pull/43325?

Thanks!

**Comment by ahcorde** [comment]
Hi @civerachb-cpr, 

please open the PR with the `camera_info_manager_py` package, I will take care of blooming the package and possible PRs.

**Comment by civerachb-cpr** [comment]
@ahcorde , done! I've made two MRs, one for humble and one for jazzy:
- https://github.com/ros-perception/image_common/pull/332
- https://github.com/ros-perception/image_common/pull/333

We've been using the `clearpathrobotics/camera_info_manager_py/ros2` branch successfully for both distros, so the code is identical. I've set the `camera_info_manager_py` package version to match with the current version of the other packages in each branch to hopefully make blooming easier for you.

**Comment by ahcorde** [comment]
Releases 
 - Rolling https://github.com/ros/rosdistro/pull/43668
 - Jazzy https://github.com/ros/rosdistro/pull/43696
 - Humble https://github.com/ros/rosdistro/pull/43697
