### ISSUE TITLE
I got some weird error.. 

### ISSUE THREAD

**Issue by caemoon2** [ros-perception/image_common#39]
when I tried to run following command,
rosrun  camera_calibration_parsers convert  ost.ini cal.yml  

I got the result like this,
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: No such file or directory
Aborted (core dumped)

and I don't know what happen and how to fix it.... I google for an hour to find any similar issues but I couldn't find anything and I"m really beginner of ROS and Linux.... So could you anybody help me to solve this problem? 
When I tried the command first, it worked. but after weekends, it doesn't work anymore..

**Comment by vrabaud** [comment]
can you please send on my personal email, the ost.ini, thx.

**Comment by caemoon2** [comment]
I sent you an email with my ost.ini file. please check it.

**Comment by vrabaud** [comment]
thx for helping me out. I will release the fix now
