### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by hgaiser** [ros-perception/image_common#59]
Hey,

Similarly to [this issue](https://github.com/ros-perception/vision_opencv/issues/158) in `cv_bridge`, this package is not python3 compatible. The lines which assume python 2.7 are [here](https://github.com/ros-perception/image_common/blob/hydro-devel/camera_calibration_parsers/CMakeLists.txt#L6-L7). I'll leave more details in the `cv_bridge` issue.

Best regards,
Hans

**Comment by vrabaud** [comment]
Thx for reporting all those bugs and providing a lot of analysis !

**Comment by hgaiser** [comment]
No problem, I'm just happy to see it being resolved quickly ;)
