### ISSUE TITLE
List transports not discovering plugins

### ISSUE THREAD

**Issue by stonier** [ros-perception/image_common#6]
I've got shadow-fixed debs for ros-groovy-image-common (1.9.22) and ros-groovy-image-transport-plugins (1.8.12) installed, but the image transport mechanism is not discovering the plugins.

Subsequently, it seems the non-raw transports are never getting created.

Is this a bug?

```
> rospack find compressed_image_transport
/opt/ros/groovy/share/compressed_image_transport
```

```
> rosrun image_transport list_transports
Declared transports:
image_transport/raw

Details:
----------
"image_transport/raw"
 - Provided by package: image_transport
 - Publisher: This is the default publisher. It publishes the Image as-is on the base topic.
 - Subscriber: This is the default pass-through subscriber for topics of type sensor_msgs/Image.
snorri@snorriheim:~$ date
Sat Dec 29 01:16:49 KST 2012
```

**Comment by vrabaud** [comment]
This issue was actually in image_transport_plugins at https://github.com/ros-perception/image_transport_plugins
b308b4223db43700288980a8d1a980c8e25cf208 fixes it.

**Comment by vrabaud** [comment]
1.8.15 of ros-groovy-image-transport-plugins fixes it for me

**Comment by stonier** [comment]
Awesome, fixes it for me too...thanks!
