### ISSUE TITLE
Several camera info managers

### ISSUE THREAD

**Issue by arnasIV** [ros-perception/image_common#64]
If I create two camera info managers in the same place of my program/ in the same node and I want to be able to set camera info for each of two cameras (left and right), i. e. use service left/set_camera_info and right/set_camera_info, how do I add this /left or /right namespace?

ros::NodeHandle &nh = getNodeHandle();
camera_info_manager::CameraInfoManager(nh, left_name, left_camera_info_url) left;
camera_info_manager::CameraInfoManager(nh, right_name, right_camera_info_url) right;

**Comment by jack-oquin** [comment]
Define node handles for the two subordinate name spaces.

This question would be better asked on answers.ros.org.

**Comment by jack-oquin** [comment]
We try to restrict issues to bugs and enhancement requests.

**Comment by arnasIV** [comment]
Sorry, but I tried and it did not work.
