### ISSUE TITLE
Release image_common into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-perception/image_common#75]
This is a friendly reminder that the Melodic buildfarm is [now available](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248).  It would be great to have a release of `image_common` into Melodic, as it is currently directly blocking 25 packages and indirectly blocking 44 packages (http://repositories.ros.org/status_page/blocked_releases_melodic.html).  Thank you!

**Comment by jack-oquin** [comment]
@vrabaud: I'll release this, if you want.

**Comment by jack-oquin** [comment]
I went ahead an did it, just now. Seemed like the right thing to do.
