### ISSUE TITLE
Installation Image_transport package on Raspberry PI

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [ros-perception/image_common#76]
Hello,

Distributions :kinetic
Raspberry pi : Jessie

May I know how to install this package on Raspberry Pi? What is the command?

**Comment by jack-oquin** [comment]
http://wiki.ros.org/kinetic/Installation/Debian

**Comment by ajal-fh** [comment]
the memory was getting exhausted while running catkin_make.

running catkin_make multiple times helped in building the package.

os: raspbian Stretch
